  },
  {
    "username": "Shocked",
    "anime_from": "Ou Dorobou Jing",
    "anime_to": "Kino no Tabi: The Beautiful World",
  },
  {

In [ ]:
import pandas as pd   
memories_df = pd.read_csv("../datasets/mal_2023/1000/animes_users_merged.csv")
users_df = pd.read_csv("../datasets/mal_2023/1000/users.csv")
anime_df = pd.read_csv("../datasets/mal_2023/1000/animes.csv")
users_df['username_lower'] = users_df['username'].str.lower()
anime_df['name_lower'] = anime_df['name'].str.lower()
memories_df['username_lower'] = memories_df['username'].str.lower()

In [ ]:
users_df[users_df['username'] == "callen8yam2"]

,mal_id,username,gender,birthday,location,joined,days_watched,mean_score,watching,completed,on_hold,dropped,plan_to_watch,total_entries,rewatched,episodes_watched,username_lower
31,6066,callen8yam2,Female,1993-07-25T00:00:00+00:00,Israel,2007-06-22T00:00:00+00:00,90.4,7.6,3.0,251.0,3.0,6.0,32.0,295.0,0.0,5242.0,callen8yam2

In [ ]:
anime_df[anime_df['name'] == "HinoKahoko"]

,anime_id,name,score,genres,english_name,japanese_name,sypnopsis,type,episodes,aired,...,rating,ranked,popularity,members,favorites,watching,completed,on-hold,dropped,name_lower
720,2924,ef: A Tale of Memories.,7.95,"Mystery, Drama, Romance",ef - a tale of memories.,ef - a tale of memories.,"On Christmas Eve, Hiro Hirono runs into Miyako...",TV,12,"Oct 7, 2007 to Dec 23, 2007",...,PG-13 - Teens 13 or older,593.0,664,220459,2834,8249,117366,7438,6403,ef: a tale of memories.

In [1]:
from tools import *
print(find_recs_from_profile_peers_who_watched_anime("Shocked", "One Piece"))
#find_recommendations_from_opinion_peers("Mara-ChanXXX", "Princess Road: Bara to Dokuro no Monshou", k=30)

RECOMMENDATIONS FOR 'SHOCKED' FROM 29 USERS:
============================================================
1. Bleach Movie 1: Memories of Nobody
2. xxxHOLiC Movie: Manatsu no Yoru no Yume
3. Fullmetal Alchemist: The Conqueror of Shamballa
4. Dragon Ball Kai
5. Bleach Movie 3: Fade to Black - Kimi no Na wo Yobu
6. Suzumiya Haruhi-chan no Yuuutsu
7. Eve no Jikan
8. Project ARMS
9. Higurashi no Naku Koro ni Rei
10. Love Hina Christmas Special: Silent Eve